[project]
name = "my_first_fastapi"
version = "0.1.0"
description = "My first fastapi backend-service and react frontend-client"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "requests>=2.32.5",
    "uvicorn>=0.35.0",
]
